os:
  - osx
language: swift
osx_image: xcode9.4
install: swift package update
before_install:
  - brew update
  - brew install zmq
  - gem install danger
  - gem install danger-swiftlint
script:
  - danger
  - swift build