os:
  - osx
language: swift
osx_image: xcode9.4
install: swift package update
before_install:
  - brew update
  - brew install zmq
  - brew install danger
script:
  - bundle exec danger
  - swift build
