os:
  - osx
language: swift
osx_image: xcode9.4
install: swift package update
before_install:
  - brew update
  - brew install zmq
  - brew reinstall swiftlint
  - bundler install
script:
  - bundler exec danger
  - swift build